### PR TITLE
Updated to new API version

### PR DESCRIPTION
**Pull request by Lewimaron**
Added support for ARK API version 2.71

### CODE REVIEW

**Comment by ark-mod** [comment]
Looks solid! I don't have the ability to compile or test it but I'll merge it anyway.

**Comment by Lewimaron** [comment]
I've got a compiled release posted up on my fork here:
https://github.com/Lewimaron/ArkModifiedSpawnLevelDistribution/releases/tag/1.0

Also, both the open issues should now be solved.

Would you like me to post this version on the ARK API website so people can find it easier?

**Comment by ark-mod** [comment]
Sorry for taking so long to answer! I am unable to maintain these projects any longer so please feel free to do whatever you feel is best for the community with regards to posting them on ARK API website etc.

If you wish I can add you as a collaborator on this repository or you can keep your fork as the primary up-to-date version going forward.

**Comment by Lewimaron** [comment]
I guess it'll be easier just to keep the fork up to date

**Pull request merged**
